# Generated by Django 5.0 on 2024-01-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='initial_deposit_date',
            new_name='initial_deposite_date',
        ),
    ]
